=== memethief/wipcomix/DTD/comicstrip.dtd
<!ELEMENT comicstrip (striptitle,strippubdate,(panel|paneltext)+,playerdef*)>
<!ELEMENT striptitle (#PCDATA)>
<!ELEMENT strippubdate (#PCDATA)>

<!ELEMENT panel (player|paneltext)*>
<!ATTLIST panel xoffset CDATA "0">
<!ATTLIST panel yoffset CDATA "0">
<!ATTLIST panel xsize CDATA #IMPLIED>
<!ATTLIST panel ysize CDATA #IMPLIED>

<!ELEMENT paneltext (#PCDATA)>
<!ATTLIST paneltext xoffset CDATA "0">
<!ATTLIST paneltext yoffset CDATA "0">
<!ATTLIST paneltext xsize CDATA #IMPLIED>
<!ATTLIST paneltext ysize CDATA #IMPLIED>
<!ATTLIST paneltext style CDATA "">

<!ELEMENT player EMPTY>
<!ATTLIST player name IDREF #REQUIRED>
<!ATTLIST player xoffset CDATA "0">
<!ATTLIST player yoffset CDATA "0">
<!ATTLIST player mood CDATA #IMPLIED>
<!ATTLIST player facing CDATA "0">

<!ELEMENT playerdef EMPTY>
<!ATTLIST playerdef id ID #REQUIRED>
<!ATTLIST playerdef source (inline|local|remote) "inline">
<!ATTLIST playerdef href CDATA #IMPLIED>

=== memethief/wipcomix/strips/strip_latest.xml
<?xml version="1.0"?>
<!DOCTYPE comicstrip SYSTEM "../DTD/comicstrip.dtd">
<!--
 Sample XML file for a plot of the programmatical comic.

Here we lay out the characters used, the storyline and the layout.
 -->
<!--
xmlns="http://fsckme.com/comic"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="../comicstrip.xsd"
 -->
<comicstrip>

<striptitle>Comic XML test</striptitle>
<strippubdate>2099-12-31</strippubdate>

<paneltext xoffset="10" yoffset="10" xsize="270" ysize="20">Our heroes struggle to speak...</paneltext>
<panel xoffset="0" yoffset="0" xsize="400" ysize="300">
	<player name="Dave" xoffset="150" yoffset="100" mood="0" facing="1"/>
	<player name="Jan" xoffset="250" yoffset="100" mood="3" facing="-1"/>
	<paneltext xoffset="110" yoffset="200" xsize="70" ysize="20">Mmrph!</paneltext>
	<paneltext xoffset="225" yoffset="200" xsize="60" ysize="20">Hmph!</paneltext>
</panel>

<paneltext xoffset="370" yoffset="270" xsize="250" ysize="20">...but find themselves mute.</paneltext>
<panel xoffset="380" yoffset="10" xsize="250" ysize="300">
	<player name="Jan" xoffset="150" yoffset="100" mood="1" facing="-1"/>
	<paneltext xoffset="120" yoffset="210" xsize="85" ysize="20">Mrrmph?!</paneltext>
</panel>

<panel xoffset="10" yoffset="300" xsize="250" ysize="290">
	<player name="Jan" xoffset="150" yoffset="100" mood="4" facing="1"/>
	<paneltext xoffset="120" yoffset="210" xsize="85" ysize="20">Hmmck!!</paneltext>
</panel>

<playerdef id="Dave" source="local" href="dave.xml" />
<playerdef id="Jan" source="local" href="jan.xml" />
 
</comicstrip>
